from xgboost import XGBClassifier

WHATSAPP_ID = "******************"
PHONE_NUMBER = "+***************"

COLUMNS_TO_MERGE_AFTER_NORMALIZED = [
    "did_break_highest_all_time_amzn",
    "did_break_highest_all_time_tsla",
    "did_break_highest_all_time_msft",
    "did_break_highest_all_time_fb",
    "did_break_highest_all_time_googl",
    "did_break_highest_all_time_aapl",
    "did_break_highest_all_time_tecs",
    "did_break_highest_all_time_spy",
    "did_break_highest_all_time_bac",
    "did_break_highest_all_time_ndaq",
    "Positive_change_in_the_last_3_day",
    "Positive_change_in_the_last_7_day",
    "did_break_highest_all_time_tqqq",
    "After Covid",
    "Weekday",
]
COLUMNS_TO_NORMALIZE = [
    "change_in_percentage_for_7_day_amzn",
    "Average_volume_for_7_day_amzn",
    "Average_close_price_for_7_day_amzn",
    "days_in_a_row_for_trend_amzn",
    "previous_days_in_a_row_for_trend_amzn",
    "change_in_percentage_for_7_day_tsla",
    "Average_volume_for_7_day_tsla",
    "Average_close_price_for_7_day_tsla",
    "days_in_a_row_for_trend_tsla",
    "previous_days_in_a_row_for_trend_tsla",
    "change_in_percentage_for_7_day_msft",
    "Average_volume_for_7_day_msft",
    "Average_close_price_for_7_day_msft",
    "days_in_a_row_for_trend_msft",
    "previous_days_in_a_row_for_trend_msft",
    "change_in_percentage_for_7_day_fb",
    "Average_volume_for_7_day_fb",
    "Average_close_price_for_7_day_fb",
    "days_in_a_row_for_trend_fb",
    "previous_days_in_a_row_for_trend_fb",
    "change_in_percentage_for_7_day_googl",
    "Average_volume_for_7_day_googl",
    "Average_close_price_for_7_day_googl",
    "days_in_a_row_for_trend_googl",
    "previous_days_in_a_row_for_trend_googl",
    "change_in_percentage_for_7_day_aapl",
    "Average_volume_for_7_day_aapl",
    "Average_close_price_for_7_day_aapl",
    "days_in_a_row_for_trend_aapl",
    "previous_days_in_a_row_for_trend_aapl",
    "change_in_percentage_for_7_day_spy",
    "Average_close_price_for_7_day_spy",
    "days_in_a_row_for_trend_spy",
    "previous_days_in_a_row_for_trend_spy",
    "change_in_percentage_for_7_day_uvxy",
    "Average_close_price_for_7_day_uvxy",
    "days_in_a_row_for_trend_uvxy",
    "previous_days_in_a_row_for_trend_uvxy",
    "change_in_percentage_for_7_day_tqqq",
    "Average_close_price_for_7_day_tqqq",
    "days_in_a_row_for_trend_tqqq",
    "previous_days_in_a_row_for_trend_tqqq",
    "change_in_percentage_for_7_day_bac",
    "Average_volume_for_7_day_bac",
    "Average_close_price_for_7_day_bac",
    "days_in_a_row_for_trend_bac",
    "previous_days_in_a_row_for_trend_bac",
    "change_in_percentage_for_7_day_ndaq",
    "Average_volume_for_7_day_ndaq",
    "Average_close_price_for_7_day_ndaq",
    "days_in_a_row_for_trend_ndaq",
    "previous_days_in_a_row_for_trend_ndaq",
    "change_in_percentage_for_7_day_tecs",
    "Average_volume_for_7_day_tecs",
    "Average_close_price_for_7_day_tecs",
    "days_in_a_row_for_trend_tecs",
    "previous_days_in_a_row_for_trend_tecs",
]
COLUMNS_FOR_X = [
    "did_break_highest_all_time_amzn",
    "did_break_highest_all_time_tsla",
    "did_break_highest_all_time_msft",
    "did_break_highest_all_time_fb",
    "did_break_highest_all_time_googl",
    "did_break_highest_all_time_aapl",
    "did_break_highest_all_time_bac",
    "did_break_highest_all_time_ndaq",
    "did_break_highest_all_time_tecs",
    "Positive_change_in_the_last_3_day",
    "Positive_change_in_the_last_7_day",
    "did_break_highest_all_time_tqqq",
    "did_break_highest_all_time_spy",
    "change_in_percentage_for_7_day_amzn",
    "Average_volume_for_7_day_amzn",
    "Average_close_price_for_7_day_amzn",
    "days_in_a_row_for_trend_amzn",
    "previous_days_in_a_row_for_trend_amzn",
    "change_in_percentage_for_7_day_tsla",
    "Average_volume_for_7_day_tsla",
    "Average_close_price_for_7_day_tsla",
    "days_in_a_row_for_trend_tsla",
    "previous_days_in_a_row_for_trend_tsla",
    "change_in_percentage_for_7_day_msft",
    "Average_volume_for_7_day_msft",
    "Average_close_price_for_7_day_msft",
    "days_in_a_row_for_trend_msft",
    "previous_days_in_a_row_for_trend_msft",
    "change_in_percentage_for_7_day_fb",
    "Average_volume_for_7_day_fb",
    "Average_close_price_for_7_day_fb",
    "days_in_a_row_for_trend_fb",
    "previous_days_in_a_row_for_trend_fb",
    "change_in_percentage_for_7_day_googl",
    "Average_volume_for_7_day_googl",
    "Average_close_price_for_7_day_googl",
    "days_in_a_row_for_trend_googl",
    "previous_days_in_a_row_for_trend_googl",
    "change_in_percentage_for_7_day_aapl",
    "Average_volume_for_7_day_aapl",
    "Average_close_price_for_7_day_aapl",
    "days_in_a_row_for_trend_aapl",
    "previous_days_in_a_row_for_trend_aapl",
    "change_in_percentage_for_7_day_spy",
    "Average_close_price_for_7_day_spy",
    "days_in_a_row_for_trend_spy",
    "previous_days_in_a_row_for_trend_spy",
    "change_in_percentage_for_7_day_uvxy",
    "Average_close_price_for_7_day_uvxy",
    "days_in_a_row_for_trend_uvxy",
    "previous_days_in_a_row_for_trend_uvxy",
    "change_in_percentage_for_7_day_tqqq",
    "Average_close_price_for_7_day_tqqq",
    "days_in_a_row_for_trend_tqqq",
    "previous_days_in_a_row_for_trend_tqqq",
    "change_in_percentage_for_7_day_bac",
    "Average_volume_for_7_day_bac",
    "Average_close_price_for_7_day_bac",
    "days_in_a_row_for_trend_bac",
    "previous_days_in_a_row_for_trend_bac",
    "change_in_percentage_for_7_day_ndaq",
    "Average_volume_for_7_day_ndaq",
    "Average_close_price_for_7_day_ndaq",
    "days_in_a_row_for_trend_ndaq",
    "previous_days_in_a_row_for_trend_ndaq",
    "change_in_percentage_for_7_day_tecs",
    "Average_volume_for_7_day_tecs",
    "Average_close_price_for_7_day_tecs",
    "days_in_a_row_for_trend_tecs",
    "previous_days_in_a_row_for_trend_tecs",
    "After Covid",
    "Weekday",
]
COLUMN_FOR_Y = ["label_1_day"]
POSITIVE_COLUMN_FOR_REAL_MONEY_CHECK = "tqqq_change_for_1_day"
NEGATIVE_COLUMN_FOR_REAL_MONEY_CHECK = "sqqq_change_for_1_day"
NEW_COLUMN_FOR_X_TEMP = COLUMNS_FOR_X.copy()
REMOVE_LST = [
    "did_break_highest_all_time_amzn",
    "did_break_highest_all_time_tsla",
    "did_break_highest_all_time_msft",
    "did_break_highest_all_time_fb",
    "did_break_highest_all_time_googl",
    "did_break_highest_all_time_aapl",
    "did_break_highest_all_time_bac",
    "did_break_highest_all_time_ndaq",
    "did_break_highest_all_time_tecs",
    "Positive_change_in_the_last_7_day",
    "Positive_change_in_the_last_3_day",
    "did_break_highest_all_time_tqqq",
    "did_break_highest_all_time_spy",
    "change_in_percentage_for_7_day_amzn",
    "Average_volume_for_7_day_amzn",
    "Average_close_price_for_7_day_amzn",
    "days_in_a_row_for_trend_amzn",
    "previous_days_in_a_row_for_trend_amzn",
    "change_in_percentage_for_7_day_tsla",
    "Average_volume_for_7_day_tsla",
    "Average_close_price_for_7_day_tsla",
    "days_in_a_row_for_trend_tsla",
    "previous_days_in_a_row_for_trend_tsla",
    "Average_volume_for_7_day_msft",
    "Average_close_price_for_7_day_msft",
    "previous_days_in_a_row_for_trend_msft",
    "change_in_percentage_for_7_day_fb",
    "Average_volume_for_7_day_fb",
    "Average_close_price_for_7_day_fb",
    "previous_days_in_a_row_for_trend_fb",
    "change_in_percentage_for_7_day_googl",
    "Average_volume_for_7_day_googl",
    "Average_close_price_for_7_day_googl",
    "days_in_a_row_for_trend_googl",
    "previous_days_in_a_row_for_trend_googl",
    "change_in_percentage_for_7_day_aapl",
    "Average_volume_for_7_day_aapl",
    "Average_close_price_for_7_day_aapl",
    "days_in_a_row_for_trend_aapl",
    "previous_days_in_a_row_for_trend_aapl",
    "change_in_percentage_for_7_day_spy",
    "Average_close_price_for_7_day_spy",
    "days_in_a_row_for_trend_spy",
    "previous_days_in_a_row_for_trend_spy",
    "change_in_percentage_for_7_day_uvxy",
    "Average_close_price_for_7_day_uvxy",
    "days_in_a_row_for_trend_uvxy",
    "previous_days_in_a_row_for_trend_uvxy",
    "Average_close_price_for_7_day_tqqq",
    "change_in_percentage_for_7_day_bac",
    "Average_volume_for_7_day_bac",
    "Average_close_price_for_7_day_bac",
    "days_in_a_row_for_trend_bac",
    "previous_days_in_a_row_for_trend_bac",
    "change_in_percentage_for_7_day_ndaq",
    "Average_volume_for_7_day_ndaq",
    "Average_close_price_for_7_day_ndaq",
    "days_in_a_row_for_trend_ndaq",
    "Average_volume_for_7_day_tecs",
    "Average_close_price_for_7_day_tecs",
    "days_in_a_row_for_trend_tecs",
    "previous_days_in_a_row_for_trend_tecs",
    "After Covid",
]
for i in REMOVE_LST:
    NEW_COLUMN_FOR_X_TEMP.remove(i)
XGB_CLF = XGBClassifier(verbosity=0)

GROUP_NAME = "test group"
PRIVATE_GROUP_NAME = "Model documendation"
NO_TRADING_DAYS = [
    "2021-09-06",
    "2021-11-25",
    "2021-12-24",
    "2022-01-17",
    "2022-02-21",
    "2022-04-15",
    "2022-05-30",
    "2022-06-20",
    "2022-07-04",
    "2022-09-05",
    "2022-11-24",
    "2022-12-26",
]
YF_DF_COLS = [
    "AMZN",
    "Date",
    "AMZN_close",
    "Date",
    "AMZN_volume",
    "TSLA",
    "Date",
    "TSLA_close",
    "Date",
    "TSLA_volume",
    "MSFT",
    "Date",
    "MSFT_close",
    "Date",
    "MSFT_volume",
    "FB",
    "Date",
    "FB_close",
    "Date",
    "FB_volume",
    "GOOGL",
    "Date",
    "GOOGL_close",
    "Date",
    "GOOGL_volume",
    "AAPL",
    "Date",
    "AAPL_close",
    "Date",
    "AAPL_volume",
    "SPY",
    "Date",
    "SPY_close",
    "TQQQ",
    "Date",
    "TQQQ_close",
    "SQQQ",
    "Date",
    "SQQQ_close",
    "UVXY",
    "Date",
    "UVXY_close",
    "BAC",
    "Date",
    "BAC_close",
    "Date",
    "BAC_volume",
    "NDAQ",
    "Date",
    "NDAQ_close",
    "Date",
    "NDAQ_volume",
    "TECS",
    "Date",
    "TECS_close",
    "Date",
    "TECS_volume",
]

YF_DF_RENAME = {
    "AMZN_close": "Close",
    "AMZN_volume": "Volume",
    "TSLA_close": "Close",
    "TSLA_volume": "Volume",
    "MSFT_close": "Close",
    "MSFT_volume": "Volume",
    "FB_close": "Close",
    "FB_volume": "Volume",
    "GOOGL_close": "Close",
    "GOOGL_volume": "Volume",
    "AAPL_close": "Close",
    "AAPL_volume": "Volume",
    "SPY_close": "Close",
    "UVXY_close": "Close",
    "TQQQ_close": "Close",
    "SQQQ_close": "Close",
    "BAC_close": "Close",
    "BAC_volume": "Volume",
    "NDAQ_close": "Close",
    "NDAQ_volume": "Volume",
    "TECS_close": "Close",
    "TECS_volume": "Volume",
}

DFS_NAMES = [
    "amzn",
    "tsla",
    "msft",
    "fb",
    "googl",
    "aapl",
    "spy",
    "tqqq",
    "sqqq",
    "uvxy",
    "bac",
    "ndaq",
    "tecs",
]

CLOSE_DATA_DICT = {
    "AMZN": "AMZN_close",
    "TSLA": "TSLA_close",
    "MSFT": "MSFT_close",
    "FB": "FB_close",
    "GOOGL": "GOOGL_close",
    "AAPL": "AAPL_close",
    "SPY": "SPY_close",
    "UVXY": "UVXY_close",
    "TQQQ": "TQQQ_close",
    "SQQQ": "SQQQ_close",
    "BAC": "BAC_close",
    "NDAQ": "NDAQ_close",
    "TECS": "TECS_close",
}

VOLUME_DATA_DICT = {
    "AMZN": "AMZN_volume",
    "TSLA": "TSLA_volume",
    "MSFT": "MSFT_volume",
    "FB": "FB_volume",
    "GOOGL": "GOOGL_volume",
    "AAPL": "AAPL_volume",
    "SPY": "SPY_volume",
    "UVXY": "UVXY_volume",
    "TQQQ": "TQQQ_volume",
    "SQQQ": "SQQQ_volume",
    "BAC": "BAC_volume",
    "NDAQ": "NDAQ_volume",
    "TECS": "TECS_volume",
}
